# Generated by Django 5.1.4 on 2025-01-11 20:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Column",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("restored_at", models.DateTimeField(blank=True, null=True)),
                ("transaction_id", models.UUIDField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255)),
                ("symbol", models.CharField(max_length=10)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "build_type",
                    models.CharField(
                        choices=[("user", "User"), ("default", "Default")],
                        db_default="default",
                        default="user",
                        max_length=20,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
            options={
                "db_table": "columns",
            },
        ),
        migrations.CreateModel(
            name="Group",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("restored_at", models.DateTimeField(blank=True, null=True)),
                ("transaction_id", models.UUIDField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255)),
                (
                    "icon",
                    models.CharField(
                        choices=[
                            ("fa-solid fa-user", "User"),
                            ("fa-solid fa-users", "Users"),
                            ("fa-solid fa-heart", "Heart"),
                            ("fa-solid fa-star", "Star"),
                            ("fa-solid fa-bell", "Bell"),
                            ("fa-solid fa-envelope", "Envelope"),
                            ("fa-solid fa-calendar", "Calendar"),
                            ("fa-solid fa-cog", "Cog"),
                            ("fa-solid fa-home", "Home"),
                            ("fa-solid fa-search", "Search"),
                            ("fa-solid fa-trash", "Trash"),
                            ("fa-solid fa-edit", "Edit"),
                            ("fa-solid fa-download", "Download"),
                            ("fa-solid fa-upload", "Upload"),
                            ("fa-solid fa-camera", "Camera"),
                            ("fa-solid fa-file", "File"),
                            ("fa-solid fa-lock", "Lock"),
                            ("fa-solid fa-unlock", "Unlock"),
                            ("fa-solid fa-plus", "Plus"),
                            ("fa-solid fa-minus", "Minus"),
                            ("fa-solid fa-check", "Check"),
                            ("fa-solid fa-times", "Times"),
                            ("fa-solid fa-exclamation", "Exclamation"),
                            ("fa-solid fa-question", "Question"),
                            ("fa-solid fa-info", "Info"),
                            ("fa-solid fa-wrench", "Wrench"),
                            ("fa-solid fa-cloud", "Cloud"),
                            ("fa-solid fa-cloud-download-alt", "Cloud Download"),
                            ("fa-solid fa-cloud-upload-alt", "Cloud Upload"),
                            ("fa-solid fa-globe", "Globe"),
                            ("fa-solid fa-folder", "Folder"),
                            ("fa-solid fa-folder-open", "Folder Open"),
                            ("fa-solid fa-chart-bar", "Bar Chart"),
                            ("fa-solid fa-chart-line", "Line Chart"),
                            ("fa-solid fa-comment", "Comment"),
                            ("fa-solid fa-comments", "Comments"),
                            ("fa-solid fa-phone", "Phone"),
                            ("fa-solid fa-table", "Table"),
                            ("fa-solid fa-tag", "Tag"),
                            ("fa-solid fa-tags", "Tags"),
                            ("fa-solid fa-tools", "Tools"),
                            ("fa-solid fa-user-circle", "User Circle"),
                            ("fa-solid fa-user-check", "User Check"),
                            ("fa-solid fa-user-plus", "User Plus"),
                            ("fa-solid fa-user-minus", "User Minus"),
                            ("fa-solid fa-user-times", "User Times"),
                        ],
                        db_default="fa-solid fa-folder",
                        default="fa-solid fa-folder",
                        max_length=50,
                    ),
                ),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "build_type",
                    models.CharField(
                        choices=[("user", "User"), ("default", "Default")],
                        db_default="default",
                        default="user",
                        max_length=20,
                    ),
                ),
                ("columns", models.ManyToManyField(to="readme.column")),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
            options={
                "db_table": "groups",
            },
        ),
    ]
