# Generated by Django 5.1.4 on 2025-01-12 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("readme", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="column",
            name="icon",
            field=models.CharField(
                choices=[
                    ("fa-solid fa-heading", "Heading"),
                    ("fa-solid fa-paragraph", "Paragraph"),
                    ("fa-solid fa-list", "List"),
                    ("fa-solid fa-check", "Check"),
                    ("fa-solid fa-list-ul", "Unordered List"),
                    ("fa-solid fa-list-ol", "Ordered List"),
                    ("fa-solid fa-quote-left", "Block Quote"),
                    ("fa-solid fa-code", "Code"),
                    ("fa-solid fa-code-branch", "Multiline Code"),
                    ("fa-solid fa-grip-horizontal", "Horizontal Rule"),
                    ("fa-solid fa-italic", "Italic"),
                    ("fa-solid fa-bold", "Bold"),
                    ("fa-solid fa-strikethrough", "Strikethrough"),
                    ("fa-solid fa-underline", "Underline"),
                    ("fa-solid fa-link", "Link"),
                    ("fa-solid fa-image", "Image"),
                    ("fa-solid fa-video", "Video"),
                    ("fa-solid fa-music", "Audio"),
                    ("fa-solid fa-table", "Table"),
                    ("fa-solid fa-list-check", "Task List"),
                    ("fa-solid fa-exclamation-triangle", "Escaping"),
                    ("fa-solid fa-quote-right", "Footnotes"),
                ],
                db_default="fa-solid fa-heading",
                default="fa-solid fa-heading",
                max_length=50,
            ),
        ),
    ]
