# Generated by Django 5.1.4 on 2025-01-12 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("readme", "0002_column_icon"),
    ]

    operations = [
        migrations.AddField(
            model_name="column",
            name="type",
            field=models.CharField(
                choices=[("basic", "Basic"), ("component", "Component")],
                db_default="basic",
                default="basic",
                max_length=20,
            ),
        ),
    ]
