# Generated by Django 5.1.4 on 2025-01-12 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("readme", "0003_column_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="column",
            name="symbol",
            field=models.CharField(
                choices=[
                    ("#", "Heading 1"),
                    ("##", "Heading 2"),
                    ("###", "Heading 3"),
                    ("####", "Heading 4"),
                    ("#####", "Heading 5"),
                    ("######", "Heading 6"),
                    ("", "Paragraph"),
                    ("-", "Unordered List (-)"),
                    ("*", "Unordered List (*)"),
                    ("+", "Unordered List (+)"),
                    ("1.", "Ordered List"),
                    (">", "Block Quote"),
                    ("code", "Code"),
                    ("multiline_code", "Multiline Code"),
                    ("---", "Horizontal Rule"),
                    ("italic", "Italic"),
                    ("bold", "Bold"),
                    ("strikethrough", "Strikethrough"),
                    ("underline", "Underline"),
                    ("link", "Link"),
                    ("image", "Image"),
                    ("video", "Video"),
                    ("audio", "Audio"),
                    ("table", "Table"),
                    ("task_list", "Task List"),
                    ("escaping", "Escaping"),
                    ("footnotes", "Footnotes"),
                ],
                max_length=50,
            ),
        ),
    ]
