# Generated by Django 5.1.4 on 2025-01-19 08:42

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("readme", "0005_readmedata"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Group",
            new_name="Section",
        ),
        migrations.AlterModelTable(
            name="section",
            table="sections",
        ),
    ]
