# Generated by Django 5.1.4 on 2025-01-19 08:49

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("readme", "0006_rename_group_section_alter_section_table"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Column",
            new_name="Component",
        ),
        migrations.AlterModelTable(
            name="component",
            table="components",
        ),
    ]
